from datetime import timedelta


from core.singletones import unlimited
from core.models.permissions import Permissions


permissions_list: dict[str, Permissions] = {
    "main_admin": Permissions(
        ban_members=True,
        unban_members=True,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=unlimited,
        max_bans_per_day=unlimited,
        max_mut_duration=unlimited,
        max_muts_per_day=unlimited,
        priority=9,
    ),
    "major_admin": Permissions(
        ban_members=True,
        unban_members=True,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=timedelta(days=365),
        max_bans_per_day=15,
        max_mut_duration=timedelta(weeks=1),
        max_muts_per_day=20,
        priority=8,
    ),
    "admin": Permissions(
        ban_members=True,
        unban_members=True,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=timedelta(weeks=4),
        max_bans_per_day=10,
        max_mut_duration=timedelta(weeks=1),
        max_muts_per_day=20,
        priority=7,
    ),
    "minor_admin": Permissions(
        ban_members=True,
        unban_members=True,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=timedelta(weeks=1),
        max_bans_per_day=5,
        max_mut_duration=timedelta(weeks=1),
        max_muts_per_day=20,
        priority=5,
    ),
    "main_moder": Permissions(
        ban_members=False,
        unban_members=False,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=timedelta(),
        max_bans_per_day=0,
        max_mut_duration=timedelta(weeks=1),
        max_muts_per_day=20,
        priority=4,
    ),
    "major_moder": Permissions(
        ban_members=False,
        unban_members=False,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=timedelta(),
        max_bans_per_day=0,
        max_mut_duration=timedelta(hours=12),
        max_muts_per_day=10,
        priority=3,
    ),
    "moder": Permissions(
        ban_members=False,
        unban_members=False,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=timedelta(),
        max_bans_per_day=0,
        max_mut_duration=timedelta(hours=6),
        max_muts_per_day=5,
        priority=2,
    ),
    "minor_moder": Permissions(
        ban_members=False,
        unban_members=False,
        mute_members=True,
        unmute_members=True,
        max_ban_duration=timedelta(),
        max_bans_per_day=0,
        max_mut_duration=timedelta(hours=1),
        max_muts_per_day=1,
        priority=1,
    ),
    "member": Permissions(
        ban_members=False,
        unban_members=False,
        mute_members=False,
        unmute_members=False,
        max_ban_duration=timedelta(),
        max_bans_per_day=0,
        max_mut_duration=timedelta(),
        max_muts_per_day=0,
        priority=0,
    ),
}
