-- 
-- depends: 20260122_01_1mPvH

CREATE TABLE bans (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    expires_at DATETIME NOT NULL,
    reason VARCHAR(64) DEFAULT "",
    FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE guilds
ADD COLUMN ban_role_id BIGINT NULL,
ADD COLUMN banning_enabled BIGINT NULL;