"""fix

Revision ID: 5c85924a5c84
Revises: 
Create Date: 2025-09-08 20:31:22.864590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c85924a5c84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=False),
    sa.Column('greetings_channel_id', sa.BIGINT(), nullable=True),
    sa.Column('ai_channel_id', sa.BIGINT(), nullable=True),
    sa.Column('activist_role_id', sa.BIGINT(), nullable=True),
    sa.Column('activist_role_messages_count', sa.Integer(), nullable=True),
    sa.Column('is_greetings_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_activist_role_extraditing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_index(op.f('ix_guilds_settings_id'), 'guilds_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('discord_id', sa.BIGINT(), nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('current_personality_name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guilds_settings_id'), table_name='guilds_settings')
    op.drop_table('guilds_settings')
    # ### end Alembic commands ###
