"""fix

Revision ID: 69a0c5bc2081
Revises: 5c85924a5c84
Create Date: 2025-09-10 21:23:09.178069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69a0c5bc2081'
down_revision: Union[str, Sequence[str], None] = '5c85924a5c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guilds_settings_id'), table_name='guilds_settings')
    op.drop_column('guilds_settings', 'id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('guilds_settings', sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_guilds_settings_id'), 'guilds_settings', ['id'], unique=False)
    # ### end Alembic commands ###
