"""fix

Revision ID: 838ce25220c0
Revises: 69a0c5bc2081
Create Date: 2025-09-10 22:21:14.512190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838ce25220c0'
down_revision: Union[str, Sequence[str], None] = '69a0c5bc2081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds_settings', sa.Column('developer_role_id', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds_settings', 'developer_role_id')
    # ### end Alembic commands ###
