"""fix_users

Revision ID: 8466587e7bdf
Revises: 838ce25220c0
Create Date: 2025-09-28 18:19:08.708598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8466587e7bdf'
down_revision: Union[str, Sequence[str], None] = '838ce25220c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('discord_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('discord_id'), 'users', ['discord_id'], unique=True)
    # ### end Alembic commands ###
