"""fix_users

Revision ID: 9b4e0c3c0453
Revises: 8466587e7bdf
Create Date: 2025-09-28 18:24:29.360948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4e0c3c0453'
down_revision: Union[str, Sequence[str], None] = '8466587e7bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_discord_id_guild_id', 'users', ['discord_id', 'guild_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_discord_id_guild_id', 'users', type_='unique')
    # ### end Alembic commands ###
